{{- if .Values.ingressController.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx-ingress-controller
        image: {{ .Values.ingressController.image }}:{{ .Values.ingressController.imageTag }}
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --publish-service=$(POD_NAMESPACE)/nginx-ingress-controller
        - --election-id=ingress-controller-leader
        - --ingress-class=nginx
        - --configmap=$(POD_NAMESPACE)/nginx-configuration
        resources:
{{ toYaml .Values.ingressController.resources | indent 10 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.ingressController.service.type }}
  selector:
    app: nginx-ingress
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meeting-room-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /api/auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /api/users(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /api/rooms(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: room-service
            port:
              number: 80
      - path: /api/reservations(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: reservation-service
            port:
              number: 80
      - path: /api/availability(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: reservation-service
            port:
              number: 80
{{- end }}